name: Bug Report
description: Something isn't working right
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Alpine)
        - Linux (Void)
        - Linux (Gentoo)
        - Linux (NixOS)
        - Windows
        - FreeBSD
        - Other
    validations:
      required: true
  - type: input
    id: gowall-version
    attributes:
      label: gowall version
      placeholder: "output of `gowall -v`"
    validations:
      required: true
  - type: input
    id: gowall-install-method
    attributes:
      label: How did you install gowall in your OS?
      placeholder: "clone and built the repo? grabbed the binaries from the release section? used a package manager?"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce??
      placeholder: e.g. step 1... step 2 ...
  - type: textarea
    id: logs
    attributes:
      label: Any error output?
      render: shell